/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CRouteImport } from './routes/c'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'

const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => CRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c': typeof CRouteWithChildren
  '/c/$threadId': typeof CThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c': typeof CRouteWithChildren
  '/c/$threadId': typeof CThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c': typeof CRouteWithChildren
  '/c/$threadId': typeof CThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c' | '/c/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c' | '/c/$threadId'
  id: '__root__' | '/' | '/c' | '/c/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CRoute: typeof CRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof CRoute
    }
  }
}

interface CRouteChildren {
  CThreadIdRoute: typeof CThreadIdRoute
}

const CRouteChildren: CRouteChildren = {
  CThreadIdRoute: CThreadIdRoute,
}

const CRouteWithChildren = CRoute._addFileChildren(CRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CRoute: CRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
