/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CRouteImport } from './routes/c'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionSuccessRouteImport } from './routes/subscription.success'
import { Route as CThreadIdRouteImport } from './routes/c.$threadId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionSuccessRoute = SubscriptionSuccessRouteImport.update({
  id: '/subscription/success',
  path: '/subscription/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CThreadIdRoute = CThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => CRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c': typeof CRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/pronunciation': typeof PronunciationRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c': typeof CRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/pronunciation': typeof PronunciationRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c': typeof CRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/pronunciation': typeof PronunciationRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$threadId': typeof CThreadIdRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c'
    | '/login'
    | '/pricing'
    | '/pronunciation'
    | '/register'
    | '/settings'
    | '/auth/callback'
    | '/c/$threadId'
    | '/subscription/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c'
    | '/login'
    | '/pricing'
    | '/pronunciation'
    | '/register'
    | '/settings'
    | '/auth/callback'
    | '/c/$threadId'
    | '/subscription/success'
  id:
    | '__root__'
    | '/'
    | '/c'
    | '/login'
    | '/pricing'
    | '/pronunciation'
    | '/register'
    | '/settings'
    | '/auth/callback'
    | '/c/$threadId'
    | '/subscription/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CRoute: typeof CRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PronunciationRoute: typeof PronunciationRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SubscriptionSuccessRoute: typeof SubscriptionSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/success': {
      id: '/subscription/success'
      path: '/subscription/success'
      fullPath: '/subscription/success'
      preLoaderRoute: typeof SubscriptionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$threadId': {
      id: '/c/$threadId'
      path: '/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof CThreadIdRouteImport
      parentRoute: typeof CRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CRouteChildren {
  CThreadIdRoute: typeof CThreadIdRoute
}

const CRouteChildren: CRouteChildren = {
  CThreadIdRoute: CThreadIdRoute,
}

const CRouteWithChildren = CRoute._addFileChildren(CRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CRoute: CRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PronunciationRoute: PronunciationRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SubscriptionSuccessRoute: SubscriptionSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
